name: Check Formatting

on:
  workflow_dispatch:
  pull_request:
    path: '**'

jobs:
  lint:
    name: Eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout electron-appbridge/${{ GITHUB_REF }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linter
        run: npm run format:check